### ISSUE TITLE
index.php

### ISSUE THREAD

**Issue by CalvinPradhan** [ITC4850-Spring2018-Group1/mas#10]
change the font for head "Yokota Sportsmen's Club"
Center "Club Login"
Consistent Font
Use Form

**Comment by richarro** [comment]
Adding php to index.php; no coding changes until php is added

**Comment by richarro** [comment]
Used the bootstrap login form and styling.

**Comment by richarro** [comment]
ready for retest

**Comment by nabdalla617** [comment]
The index looking good.
