### ISSUE TITLE
admin_post_sales_checkout.php

### ISSUE THREAD

**Issue by richarro** [ITC4850-Spring2018-Group1/mas#21]
Create validation rules: 
1. if serial # is already attached to a member, then should not see it in the list (FIXED)
2. name must be selected along with serial # to complete checkout (FIXED)
3. validate amount field, ie., must be in format of XXXX.XX

**Comment by richarro** [comment]
FIRST VALIDATION ISSUE IS NOW RESOLVED (RETEST)

**Comment by richarro** [comment]
issue #3 is the only validation outstanding: validate amount field, ie., must be in format of XXXX.XX. 4/5 due date.

**Comment by richarro** [comment]
<input type="number" required name="amount" min="0.01" step="0.01" placeholder="00.00">

**Comment by nabdalla617** [comment]
The amount format showing 00.00 when blank
