### ISSUE TITLE
user_view_amounts_paid.php

### ISSUE THREAD

**Issue by richarro** [ITC4850-Spring2018-Group1/mas#33]
correct action link to link to receipt using receipt # not mem_no

**Comment by richarro** [comment]
`echo '<td><a class="btn" href="admin_user_receipt.php?rec_receipt_no='.$row['rec_receipt_no'].'">Print<br>Receipt</a></td>';`

**Comment by richarro** [comment]
Done, ready for retest. admin_user-receipt.php needs to modified to use the variable but link itself is working.

**Comment by nabdalla617** [comment]
The path is working.
