### ISSUE TITLE
user_view_update_ATF_status.php

### ISSUE THREAD

**Issue by richarro** [ITC4850-Spring2018-Group1/mas#35]
add action column to the table to allow updates to individual records in the table.

**Comment by richarro** [comment]
DONE. ADDED WHEN UPDATED CODE TO FILTER ON LOGGED IN MEMBER NAME VIA THE SESSION. SEPARATE ISSUE WILL BE LOGGED TO INVOKE THE UPDATE LINK.

**Comment by richarro** [comment]
ready for retest

**Comment by nabdalla617** [comment]
This works fine
