### ISSUE TITLE
admin_report_quarterly_financial_statement.php

### ISSUE THREAD

**Issue by richarro** [ITC4850-Spring2018-Group1/mas#44]
The requested URL /admin_report_quarterly_financial_statement was not found on this server.

**Comment by richarro** [comment]
We will export data instead of code page/report. Waiting on Calvin's update.

**Comment by CalvinPradhan** [comment]
retest

**Comment by richarro** [comment]
exportData page added. this needs to be tested.

**Comment by nabdalla617** [comment]
This works
