### ISSUE TITLE
admin_post_sales_checkout_success.php

### ISSUE THREAD

**Issue by richarro** [ITC4850-Spring2018-Group1/mas#62]
Research why Bluehost does not recognize header for redirects.

**Comment by richarro** [comment]
https://stackoverflow.com/questions/8215576/do-i-need-to-modify-my-bluehost-php-ini-file-header-function-not-working-on-rem

**Comment by richarro** [comment]
Try using an absolute URL for the redirect, i.e., 

header("Location: http://admin_post_sales_checkout_success.php");

**Comment by richarro** [comment]
modify code on income_expense and checkout pages to display message rather than redirect.

**Comment by richarro** [comment]
code modified on sales and post income pages. Ready for retest.

**Comment by nabdalla617** [comment]
This is all set.
