### ISSUE TITLE
admin_add_new_member.php

### ISSUE THREAD

**Issue by richarro** [ITC4850-Spring2018-Group1/mas#63]
family id# should not be created unless there is an actual family member added.

**Comment by richarro** [comment]
`if(empty($fam_fname) || empty($fam_lname)) {
	echo "<script type= 'text/javascript'>alert('Family member has not been added. Edit record to record family member first and last name.');</script>";
}
else {
	$pdoQuery3 = "INSERT INTO family (fam_fname, fam_mi, fam_lname, fam_cell_number, fam_email, fam_installation, fam_remarks, fam_assoc_mem_no) VALUES (:f_fname, :f_mi, :f_lname, :f_cell, :f_email, :f_install, :f_remarks, (LAST_INSERT_ID()))";

	$pdoResult2 = $pdoConnect->prepare($pdoQuery3);

	$pdoExec3 = $pdoResult2->execute(array(":f_fname"=>$fam_fname,":f_mi"=>$fam_mi,":f_lname"=>$fam_lname,":f_cell"=>$fam_cell,":f_email"=>$fam_email,":f_install"=>$fam_installation,":f_remarks"=>$fam_remarks));
}
`

**Comment by richarro** [comment]
ready for retest

**Comment by richarro** [comment]
assigned to Nassir

**Comment by nabdalla617** [comment]
This is all set
